### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by toby20130333** [GenaBitu/BlendSplitter#1]
I want to preview this lib's effect so can you provider some exapmles ?thanks

**Comment by marekdedic** [comment]
I have a quick&dirty repo using this, try this commit:
https://github.com/GenaBitu/NIMP/tree/a951319f0836de32bba2f28091a950f3539c243f
You need Qt creator to compile it and you need to put the library files inside the BlendSplitter directory in that repo. (There are Linux symbolic links, so if you are on Linux, just use the same directory structure...)
Does that work for you?

**Comment by toby20130333** [comment]
@GenaBitu Thank you!

**Comment by marekdedic** [comment]
Was it useful? Can I close this issue?

**Comment by toby20130333** [comment]
@GenaBitu OK close it
